name: Sync Notion PR

on:
  pull_request:
    branches: [dev]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Notion PR Sync
        uses: Slipum/sync-notion-pr@v1.0.1
        with:
          notion_token: ${{ secrets.NOTION_TOKEN }}
          notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
